
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: GitHub_Trello_WebHook_development

test:
  <<: *default
  database: GitHub_Trello_WebHook_test

production:
  <<: *default
  database: deploydemo_production

