# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d22120700c4e99c6768f2680013af53bebc153882b5a2f3b5650f50f35fd09b91a143a8a4e4d43cfa66ebf33e03448d6e42ebf47871e97114868e6291834e9

test:
  secret_key_base: b4ef3c3f19e377d1954d694250353a7e93138660a132385f3829bbb1fc54a26d445acacd222bd2e1cb88b944b472fce8b6f3115e5b6f44e7b9a6ee9941b85ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
